#!/usr/bin/env python3
"""Prepare a react-lua environment that Lune can require.

The published `@jsdotlua/*` packages are authored for Roblox and darklua, and
three of their conventions are not Lune's. None of the rewrites below touch a
line of reconciler logic — they are all module resolution:

1. **`.lua` files.** Lune resolves `.luau`. The packages ship both.
2. **Explicit extensions and `init` in require paths.** `require("./x.lua")` and
   `require("./x/init")` name a literal child to Lune; it wants `require("./x")`.
3. **`init.luau` relative requires.** Under Roblox an `init.luau` is an ordinary
   file, so `./X` is its sibling. Under Lune it *stands in for its directory*, so
   `./X` is a sibling of the directory. `./X` becomes `./<dir>/X`, and `../Y`
   becomes `./Y`.
4. **`require(script.Parent.X)`.** A Roblox instance path, which darklua would
   have rewritten at build time.

Usage:

    python scripts/prepare_react_env.py <directory>
    LUAUX_REACT=<directory> LUAUX_LUNE=$(which lune) \
      cargo test -p luaux --test runtime
"""

import io
import json
import os
import re
import subprocess
import sys

PACKAGES = ["@jsdotlua/react", "@jsdotlua/react-roblox"]

# Lune resolves an alias as a path, and wants it explicitly relative.
ALIASES = {"aliases": {"pkg": "./node_modules"}}

# Roblox globals the packages reach for, backed by Lune where it has an
# equivalent and stubbed where it does not. `getfenv()` rather than `_G`: only
# the former is the environment a free variable in another module resolves in.
SHIM = '''-- Generated by scripts/prepare_react_env.py. Do not edit.
--!nocheck
getfenv().__ROACT_17_MOCK_SCHEDULER__ = true

local roblox = require("@lune/roblox")
local serde = require("@lune/serde")

getfenv().Instance = roblox.Instance
getfenv().Color3 = roblox.Color3
getfenv().UDim = roblox.UDim
getfenv().UDim2 = roblox.UDim2
getfenv().Vector2 = roblox.Vector2
getfenv().Enum = roblox.Enum
getfenv().task = require("@lune/task")
getfenv().tick = os.clock
getfenv().time = os.clock

local services = {
\tHttpService = {
\t\tJSONEncode = function(_, value) return serde.encode("json", value) end,
\t\tJSONDecode = function(_, value) return serde.decode("json", value) end,
\t\tGenerateGUID = function() return "guid" end,
\t},
\t-- Lune has no tag registry; React only reads it, so an empty one is honest.
\tCollectionService = {
\t\tAddTag = function() end,
\t\tRemoveTag = function() end,
\t\tGetTags = function() return {} end,
\t\tGetTagged = function() return {} end,
\t\tHasTag = function() return false end,
\t},
\tRunService = {
\t\tIsRunning = function() return false end,
\t\tIsClient = function() return true end,
\t\tIsServer = function() return false end,
\t\tIsStudio = function() return false end,
\t},
}

getfenv().game = {
\tGetService = function(_, name)
\t\treturn services[name] or error("unshimmed service: " .. tostring(name))
\tend,
}
getfenv().workspace = {}

return true
'''


def run(command, cwd):
    subprocess.run(command, cwd=cwd, check=True, shell=True)


def rename_lua_to_luau(root):
    """Rename `.lua` to `.luau`, never over the top of an existing `.luau`.

    `os.rename` replaces its destination silently on POSIX, and these packages
    ship both spellings — so a collision would destroy the file Lune actually
    resolves and leave the other one in its place, with nothing said about it.
    """
    renamed, collisions = 0, []

    for base, _, files in os.walk(root):
        for name in files:
            if not name.endswith(".lua"):
                continue

            source = os.path.join(base, name)
            target = os.path.join(base, name[:-4] + ".luau")

            if os.path.exists(target):
                collisions.append(os.path.relpath(source, root))
                continue

            os.rename(source, target)
            renamed += 1

    for path in collisions:
        print("  kept the .luau beside", path)

    return renamed


def rewrite(root):
    """Rewrite require paths in place. Returns the number of files changed."""
    changed = 0

    for base, _, files in os.walk(root):
        is_init_dir = "init.luau" in files
        here = os.path.basename(base)

        for name in files:
            if not name.endswith(".luau"):
                continue

            path = os.path.join(base, name)
            try:
                source = io.open(path, encoding="utf-8").read()
            except (OSError, UnicodeDecodeError):
                continue

            text = source

            # require(script.Parent["X"]) and require(script.Parent.X)
            text = re.sub(
                r"""require\(\s*script\.Parent\[['"]([^'"]+)['"]\]\s*\)""",
                r'require("./\1")',
                text,
            )
            text = re.sub(
                r"""require\(\s*script\.Parent\.([A-Za-z_][A-Za-z0-9_]*)\s*\)""",
                r'require("./\1")',
                text,
            )

            # Explicit extensions and trailing /init.
            text = re.sub(
                r"""(require\(\s*['"][^'"]*?)\.luau?(['"]\s*\))""", r"\1\2", text
            )
            text = re.sub(
                r"""(require\(\s*['"][^'"]*?)/init(['"]\s*\))""", r"\1\2", text
            )

            # init.luau stands in for its directory under Lune.
            if is_init_dir and name == "init.luau":

                def relocate(match):
                    quote, spec = match.group(2), match.group(3)
                    if spec.startswith("../"):
                        return match.group(1) + quote + "./" + spec[3:] + quote + ")"
                    if spec.startswith("./"):
                        return (
                            match.group(1)
                            + quote
                            + "./"
                            + here
                            + "/"
                            + spec[2:]
                            + quote
                            + ")"
                        )
                    return match.group(0)

                text = re.sub(
                    r"""(require\(\s*)(['"])([^'"]+)\2\s*\)""", relocate, text
                )

            if text != source:
                io.open(path, "w", encoding="utf-8").write(text)
                changed += 1

    return changed


def write_entry_points(modules):
    """Give every package a root `init.luau` naming its entry directory.

    npm installs the source but no Lune-resolvable entry: `@pkg/@jsdotlua/react`
    is a directory whose code lives in `src/`, and Lune will not look inside.
    npmluau normally writes shims for this, and does not run reliably as a
    dependency's install script — generating them here makes the environment
    reproducible from `npm install` alone.

    The path is `./<package>/<entry>` rather than `./<entry>` because the file is
    an `init.luau`: it stands in for its own directory, so a relative path starts
    from the directory's parent.
    """
    written = 0

    for base, dirs, files in os.walk(modules):
        # Pruned before the package check, not after: placed after, a nested
        # node_modules is only skipped beneath a directory that already had a
        # package.json, which is almost never where one appears.
        dirs[:] = [d for d in dirs if d != "node_modules"]

        if "package.json" not in files:
            continue

        root = os.path.join(base, "init.luau")
        if os.path.exists(root):
            continue

        try:
            manifest = json.load(io.open(os.path.join(base, "package.json"), encoding="utf-8"))
        except (OSError, ValueError):
            continue

        main_field = (manifest.get("main") or "").replace("\\", "/")
        if not main_field:
            print("  no main field, so no entry point:", os.path.relpath(base, modules))
            continue

        # Strip the extension the rename above already changed, then point at
        # the directory when the entry is its `init` — Lune resolves a directory
        # through `init.luau` — and at the file itself otherwise. Pointing at the
        # directory unconditionally silently resolves a `main` of `src/index` to
        # `src/init`, which is a different module.
        stem = re.sub(r"\.luau?$", "", main_field)
        directory, name = os.path.split(stem)
        target = directory if name == "init" and directory else stem

        package = os.path.basename(base)
        io.open(root, "w", encoding="utf-8").write(
            "-- Generated by scripts/prepare_react_env.py. Do not edit.\n"
            'return require("./{}/{}")\n'.format(package, target)
        )
        written += 1

    return written


def main():
    if len(sys.argv) != 2:
        print(__doc__)
        return 2

    directory = os.path.abspath(sys.argv[1])
    os.makedirs(directory, exist_ok=True)

    io.open(os.path.join(directory, "package.json"), "w", encoding="utf-8").write(
        json.dumps({"name": "luaux-react-env", "private": True}, indent=2)
    )

    print("installing", ", ".join(PACKAGES))
    run("npm install --silent " + " ".join(PACKAGES), directory)

    modules = os.path.join(directory, "node_modules")
    print("renamed .lua ->.luau:", rename_lua_to_luau(modules))
    print("require paths rewritten in:", rewrite(modules), "files")
    print("entry points written:", write_entry_points(modules))

    io.open(os.path.join(directory, ".luaurc"), "w", encoding="utf-8").write(
        json.dumps(ALIASES, indent=2)
    )
    io.open(os.path.join(directory, "shim.luau"), "w", encoding="utf-8").write(SHIM)

    print("ready:", directory)
    return 0


if __name__ == "__main__":
    sys.exit(main())
